export const GET_LOGIN_REQUEST = 'USER/LOGINREQUEST';
export const GET_LOGIN_SUCCESS = 'USER/LOGINSUCCESS';
export const GET_LOGIN_FAILURE = 'USER/LOGINFAILURE';
export const LOGOUT = 'USER/LOGOUT';

export const GET_BARTERS_REQUEST = 'BARTERS/GETBARTERSREQUEST';
export const GET_BARTERS_SUCCESS = 'BARTERS/GETBARTERSSUCCESS';
export const GET_BARTERS_FAILURE = 'BARTERS/GETBARTERSFAILURE';

export const SINGLE_BARTER_REQUEST = 'BARTERS/SINGLEBARTERREQUEST';
export const SINGLE_BARTER_FAILURE = 'BARTERS/SINGLEBARTERREQUEST';
export const ADD_NEW_BARTER = 'BARTERS/ADDNEW';
export const SAVE_BARTER = 'BARTERS/SAVE';
export const DELETE_BARTER = 'BARTERS/DELETE';

export const ADD_NEW_COMMENT = 'COMMENTS/ADDNEW';
export const DELETE_COMMENT = 'COMMENTS/DELETE';
export const COMMENT_REQUEST = 'COMMENTS/COMMENTREQUEST';
export const COMMENT_FAILURE = 'COMMENTS/COMMENTFAILURE';

//BARTERS_GET_REQUEST
//BARTERS_GET_SUCCESS
//BARTERS_GET_FAILURE