export const SET_LOGIN_USER = 'USER/LOGINSET';
export const SET_COUNTRY_USER = 'USER/COUNTRYSET';
export const SET_CITY_USER = 'USER/CITYSET';
export const ADD_LOCATION_USER = 'USER/ADDLOCATION';
export const SET_CURRENT_LOCATION = 'USER/SETCURRENTLOCATION';
export const ADD_LOCATION_FROM_STORAGE = 'USER/ADDLOCATIONFROMSTORAGE';

export const GET_COUNTRIES_REQUEST = 'COUNTRIES/SENDREQUEST';
export const GET_COUNTRIES_SUCCESS = 'COUNTRIES/RESPONSESUCCESS';
export const GET_COUNTRIES_FAILURE = 'COUNTRIES/RESPONSEFILURE';

export const GET_CITIES_REQUEST = 'CITIES/SENDREQUEST';
export const GET_CITIES_SUCCESS = 'CITIES/RESPONSESUCCESS';
export const GET_CITIES_FAILURE = 'CITIES/RESPONSEFILURE';

export const GET_WEATHER_REQUEST = 'WEATHER/SENDREQUEST';
export const GET_WEATHER_SUCCESS = 'WEATHER/RESPONSESUCCESS';
export const GET_WEATHER_FAILURE = 'WEATHER/RESPONSEFILURE';
